name: lityui

services:
  frontend:
    build: .
    container_name: lityui_app
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lityui.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.lityui.entrypoints=${ENTRYPOINT}"
      # Comentar la linea de abajo si estas en local y descomentarla si estas en produccion
      - "traefik.http.routers.lityui.tls.certresolver=${CERTRESOLVER}"
      - "traefik.http.services.lityui.loadbalancer.server.port=80"

networks:
  web:
    external: true